// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.29.3
// source: public/assistant.proto

/* eslint-disable */
import type { PaginationRequest, PaginationResponse } from "../common";

/** AI Assistant configuration */
export interface Assistant {
  id: number;
  name: string;
  description: string;
  llmId?: number | undefined;
  systemPrompt: string;
  taskPrompt: string;
  starterMessages: string[];
  isDefault: boolean;
  isVisible: boolean;
  displayPriority: number;
  createdBy?: number | undefined;
  creationDate?: Date | undefined;
  lastUpdate?: Date | undefined;
}

/** Request to create a new assistant */
export interface CreateAssistantRequest {
  name: string;
  description: string;
  llmId?: number | undefined;
  systemPrompt: string;
  taskPrompt: string;
  starterMessages: string[];
  isDefault: boolean;
  isVisible: boolean;
  displayPriority: number;
}

/** Request to update an assistant */
export interface UpdateAssistantRequest {
  id: number;
  name?: string | undefined;
  description?: string | undefined;
  llmId?: number | undefined;
  systemPrompt?: string | undefined;
  taskPrompt?: string | undefined;
  starterMessages: string[];
  isDefault?: boolean | undefined;
  isVisible?: boolean | undefined;
  displayPriority?: number | undefined;
}

/** Response for GET /assistants */
export interface ListAssistantsRequest {
  pagination?:
    | PaginationRequest
    | undefined;
  /** Filter by visibility */
  isVisible?: boolean | undefined;
}

export interface ListAssistantsResponse {
  assistants: Assistant[];
  pagination?: PaginationResponse | undefined;
}

/** Response for GET /assistants/{id} */
export interface GetAssistantResponse {
  assistant?: Assistant | undefined;
}
