// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.29.3
// source: public/chat.proto

/* eslint-disable */
import type { PaginationRequest, PaginationResponse } from "../common";

/** Chat mode */
export enum ChatMode {
  CHAT_MODE_UNSPECIFIED = "CHAT_MODE_UNSPECIFIED",
  /** CHAT_MODE_CHAT - Full RAG with LLM */
  CHAT_MODE_CHAT = "CHAT_MODE_CHAT",
  /** CHAT_MODE_SEARCH - Vector search only */
  CHAT_MODE_SEARCH = "CHAT_MODE_SEARCH",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** Message role */
export enum MessageRole {
  MESSAGE_ROLE_UNSPECIFIED = "MESSAGE_ROLE_UNSPECIFIED",
  MESSAGE_ROLE_USER = "MESSAGE_ROLE_USER",
  MESSAGE_ROLE_ASSISTANT = "MESSAGE_ROLE_ASSISTANT",
  MESSAGE_ROLE_SYSTEM = "MESSAGE_ROLE_SYSTEM",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** Chat session */
export interface ChatSession {
  id: number;
  userId: number;
  assistantId: number;
  title: string;
  mode: ChatMode;
  messageCount: number;
  creationDate?: Date | undefined;
  lastUpdate?: Date | undefined;
  lastMessageAt?: Date | undefined;
}

/** Chat message */
export interface ChatMessage {
  id: number;
  chatSessionId: number;
  role: MessageRole;
  content: string;
  tokenCount: number;
  parentMessageId?: number | undefined;
  rephrasedQuery?: string | undefined;
  retrievalContext?: { [key: string]: any } | undefined;
  toolCalls?: { [key: string]: any } | undefined;
  error?: string | undefined;
  creationDate?: Date | undefined;
}

/** Source document referenced in a message */
export interface MessageSource {
  documentId: number;
  chunkId: string;
  score: number;
  title?: string | undefined;
  snippet?: string | undefined;
}

/** Message feedback */
export interface MessageFeedback {
  id: number;
  chatMessageId: number;
  userId: number;
  isPositive: boolean;
  feedbackText?: string | undefined;
  creationDate?: Date | undefined;
}

/** Request to create a new chat session */
export interface CreateChatSessionRequest {
  assistantId: number;
  title?: string | undefined;
  mode: ChatMode;
}

/** Request to list chat sessions */
export interface ListChatSessionsRequest {
  pagination?: PaginationRequest | undefined;
  assistantId?: number | undefined;
}

export interface ListChatSessionsResponse {
  sessions: ChatSession[];
  pagination?: PaginationResponse | undefined;
}

/** Response for GET /chat/sessions/{id} */
export interface GetChatSessionResponse {
  session?:
    | ChatSession
    | undefined;
  /** Last N messages */
  messages: ChatMessage[];
}

/** Request to list messages in a session */
export interface ListMessagesRequest {
  sessionId: number;
  pagination?: PaginationRequest | undefined;
}

export interface ListMessagesResponse {
  messages: ChatMessage[];
  pagination?: PaginationResponse | undefined;
}

/** Response for GET /chat/messages/{id} */
export interface GetMessageResponse {
  message?: ChatMessage | undefined;
}

/** Response for GET /chat/messages/{id}/sources */
export interface GetMessageSourcesResponse {
  sources: MessageSource[];
}

/** Request to submit feedback on a message */
export interface SubmitFeedbackRequest {
  messageId: number;
  isPositive: boolean;
  feedbackText?: string | undefined;
}

export interface SubmitFeedbackResponse {
  feedback?: MessageFeedback | undefined;
}

/** Client -> Server: Start chat */
export interface WsChatStart {
  sessionId: number;
  query: string;
  mode: ChatMode;
}

/** Client -> Server: Cancel generation */
export interface WsChatCancel {
  sessionId: number;
}

/** Server -> Client: Retrieval started */
export interface WsRetrievalStart {
  sessionId: number;
  query: string;
  rephrasedQuery: string;
}

/** Server -> Client: Retrieval complete */
export interface WsRetrievalComplete {
  sessionId: number;
  sources: MessageSource[];
}

/** Server -> Client: Generation token (streaming) */
export interface WsGenerationToken {
  sessionId: number;
  token: string;
}

/** Server -> Client: Generation complete */
export interface WsGenerationComplete {
  sessionId: number;
  messageId: number;
  tokenCount: number;
}

/** Server -> Client: Error */
export interface WsError {
  code: string;
  message: string;
}
