// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.29.3
// source: public/connector.proto

/* eslint-disable */
import type { PaginationRequest, PaginationResponse } from "../common";

/** Connector types supported in v1 */
export enum ConnectorType {
  CONNECTOR_TYPE_UNSPECIFIED = "CONNECTOR_TYPE_UNSPECIFIED",
  CONNECTOR_TYPE_TEAMS = "CONNECTOR_TYPE_TEAMS",
  CONNECTOR_TYPE_GOOGLE_DRIVE = "CONNECTOR_TYPE_GOOGLE_DRIVE",
  CONNECTOR_TYPE_ONEDRIVE = "CONNECTOR_TYPE_ONEDRIVE",
  CONNECTOR_TYPE_WEB = "CONNECTOR_TYPE_WEB",
  CONNECTOR_TYPE_FILE = "CONNECTOR_TYPE_FILE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** Connector status */
export enum ConnectorStatus {
  CONNECTOR_STATUS_UNSPECIFIED = "CONNECTOR_STATUS_UNSPECIFIED",
  CONNECTOR_STATUS_PENDING = "CONNECTOR_STATUS_PENDING",
  CONNECTOR_STATUS_SYNCING = "CONNECTOR_STATUS_SYNCING",
  CONNECTOR_STATUS_ACTIVE = "CONNECTOR_STATUS_ACTIVE",
  CONNECTOR_STATUS_ERROR = "CONNECTOR_STATUS_ERROR",
  CONNECTOR_STATUS_DISABLED = "CONNECTOR_STATUS_DISABLED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** Connector scope for vector collection routing */
export enum ConnectorScope {
  CONNECTOR_SCOPE_UNSPECIFIED = "CONNECTOR_SCOPE_UNSPECIFIED",
  CONNECTOR_SCOPE_USER = "CONNECTOR_SCOPE_USER",
  CONNECTOR_SCOPE_GROUP = "CONNECTOR_SCOPE_GROUP",
  CONNECTOR_SCOPE_ORG = "CONNECTOR_SCOPE_ORG",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** Data source connector */
export interface Connector {
  id: number;
  name: string;
  type: ConnectorType;
  /** Connector-specific configuration */
  config?:
    | { [key: string]: any }
    | undefined;
  /** Sync state (cursors, tokens, etc.) */
  state?: { [key: string]: any } | undefined;
  refreshFreqMinutes?: number | undefined;
  userId: number;
  scope: ConnectorScope;
  /** Group name if scope=GROUP */
  scopeId?: string | undefined;
  status: ConnectorStatus;
  statusMessage?: string | undefined;
  lastSyncAt?: Date | undefined;
  docsAnalyzed: number;
  creationDate?: Date | undefined;
  lastUpdate?: Date | undefined;
}

/** Request to create a new connector */
export interface CreateConnectorRequest {
  name: string;
  type: ConnectorType;
  config?: { [key: string]: any } | undefined;
  refreshFreqMinutes?: number | undefined;
  scope: ConnectorScope;
  scopeId?: string | undefined;
}

/** Request to update a connector */
export interface UpdateConnectorRequest {
  id: number;
  name?: string | undefined;
  config?: { [key: string]: any } | undefined;
  refreshFreqMinutes?: number | undefined;
  scope?: ConnectorScope | undefined;
  scopeId?: string | undefined;
}

/** Response for GET /connectors */
export interface ListConnectorsRequest {
  pagination?: PaginationRequest | undefined;
  type?: ConnectorType | undefined;
  status?: ConnectorStatus | undefined;
}

export interface ListConnectorsResponse {
  connectors: Connector[];
  pagination?: PaginationResponse | undefined;
}

/** Response for GET /connectors/{id} */
export interface GetConnectorResponse {
  connector?: Connector | undefined;
}

/** Response for POST /connectors/{id}/sync */
export interface TriggerSyncResponse {
  success: boolean;
  message: string;
}

/** Response for GET /connectors/{id}/status */
export interface GetConnectorStatusResponse {
  status: ConnectorStatus;
  statusMessage?: string | undefined;
  lastSyncAt?: Date | undefined;
  docsAnalyzed: number;
  docsPending: number;
}
