// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.29.3
// source: public/document.proto

/* eslint-disable */
import type { PaginationRequest, PaginationResponse } from "../common";

/** Document processing status */
export enum DocumentStatus {
  DOCUMENT_STATUS_UNSPECIFIED = "DOCUMENT_STATUS_UNSPECIFIED",
  DOCUMENT_STATUS_PENDING = "DOCUMENT_STATUS_PENDING",
  DOCUMENT_STATUS_PROCESSING = "DOCUMENT_STATUS_PROCESSING",
  DOCUMENT_STATUS_COMPLETED = "DOCUMENT_STATUS_COMPLETED",
  DOCUMENT_STATUS_FAILED = "DOCUMENT_STATUS_FAILED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** Document metadata */
export interface Document {
  id: number;
  parentId?: number | undefined;
  connectorId: number;
  sourceId: string;
  url?: string | undefined;
  originalUrl?: string | undefined;
  title?: string | undefined;
  contentType?: string | undefined;
  status: DocumentStatus;
  statusMessage?: string | undefined;
  chunkCount: number;
  creationDate?: Date | undefined;
  lastUpdate?: Date | undefined;
}

/** Response for GET /documents */
export interface ListDocumentsRequest {
  pagination?: PaginationRequest | undefined;
  connectorId?: number | undefined;
  status?: DocumentStatus | undefined;
}

export interface ListDocumentsResponse {
  documents: Document[];
  pagination?: PaginationResponse | undefined;
}

/** Response for GET /documents/{id} */
export interface GetDocumentResponse {
  document?: Document | undefined;
}

/** Request for GET /documents/search */
export interface SearchDocumentsRequest {
  query: string;
  connectorId?:
    | number
    | undefined;
  /** Max results (default: 10) */
  limit: number;
  /** Minimum relevance score (0-1) */
  minScore: number;
}

/** Search result with relevance score */
export interface DocumentSearchResult {
  document?: Document | undefined;
  chunkId: string;
  chunkContent: string;
  score: number;
}

export interface SearchDocumentsResponse {
  results: DocumentSearchResult[];
}
