// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.29.3
// source: public/embedding_model.proto

/* eslint-disable */

/** Embedding model configuration */
export interface EmbeddingModel {
  id: number;
  /** e.g., "sentence-transformers/paraphrase-multilingual-mpnet-base-v2" */
  modelId: string;
  /** Display name */
  modelName: string;
  /** Vector dimension (e.g., 768) */
  modelDimension: number;
  /** Optional external embedding service URL */
  endpoint?: string | undefined;
  isActive: boolean;
  creationDate?: Date | undefined;
  lastUpdate?: Date | undefined;
}

/** Request to create a new embedding model config */
export interface CreateEmbeddingModelRequest {
  modelId: string;
  modelName: string;
  modelDimension: number;
  endpoint?: string | undefined;
}

/** Response for GET /embedding-models */
export interface ListEmbeddingModelsResponse {
  models: EmbeddingModel[];
}

/** Response for GET /embedding-models/active */
export interface GetActiveEmbeddingModelResponse {
  model?: EmbeddingModel | undefined;
}

/** Response for PUT /embedding-models/{id}/activate */
export interface ActivateEmbeddingModelResponse {
  success: boolean;
  message: string;
  /** True if documents need to be re-indexed */
  requiresReindex: boolean;
  documentsAffected: number;
}
