// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.29.3
// source: public/user.proto

/* eslint-disable */
import type { PaginationRequest, PaginationResponse } from "../common";

/** User profile */
export interface User {
  id: number;
  userName: string;
  email: string;
  firstName: string;
  lastName: string;
  roles: string[];
  groups: string[];
  preferences?: UserPreferences | undefined;
  isActive: boolean;
  creationDate?: Date | undefined;
  lastUpdate?: Date | undefined;
  lastLogin?: Date | undefined;
}

/** User preferences stored as JSON in DB */
export interface UserPreferences {
  defaultAssistantId?:
    | number
    | undefined;
  /** "light", "dark", "system" */
  theme: string;
  /** Additional custom preferences */
  custom: { [key: string]: string };
}

export interface UserPreferences_CustomEntry {
  key: string;
  value: string;
}

/** Request to update current user's profile */
export interface UpdateUserRequest {
  firstName?: string | undefined;
  lastName?: string | undefined;
  preferences?: UserPreferences | undefined;
}

/** Response for GET /users/me */
export interface GetCurrentUserResponse {
  user?: User | undefined;
}

/** Response for GET /users (admin only) */
export interface ListUsersRequest {
  pagination?:
    | PaginationRequest
    | undefined;
  /** Filter by active status */
  isActive?: boolean | undefined;
}

export interface ListUsersResponse {
  users: User[];
  pagination?: PaginationResponse | undefined;
}
