// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.29.3
// source: common.proto

/* eslint-disable */

/** Pagination request parameters */
export interface PaginationRequest {
  /** Page number (1-indexed) */
  page: number;
  /** Items per page (default: 20, max: 100) */
  limit: number;
}

/** Pagination response metadata */
export interface PaginationResponse {
  /** Current page number */
  page: number;
  /** Items per page */
  limit: number;
  /** Total number of items */
  total: number;
  /** Total number of pages */
  pages: number;
}

/** Standard error response */
export interface ErrorResponse {
  /** Error code (e.g., "VALIDATION_ERROR", "NOT_FOUND") */
  code: string;
  /** Human-readable error message */
  message: string;
  /** Field-level errors for validation */
  details: FieldError[];
}

/** Field-level validation error */
export interface FieldError {
  /** Field name (e.g., "config.folder_id") */
  field: string;
  /** Error message for this field */
  message: string;
}

/** Audit fields included in all entities */
export interface AuditInfo {
  creationDate?: Date | undefined;
  lastUpdate?: Date | undefined;
  userIdLastUpdate?: number | undefined;
}

/** Empty request/response for endpoints that don't need parameters */
export interface Empty {
}

/** Generic ID wrapper */
export interface IdRequest {
  id: number;
}

/** Generic success response */
export interface SuccessResponse {
  success: boolean;
  message: string;
}
