// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.29.3

/* eslint-disable */

export * from "./google/protobuf/timestamp";
export * from "./google/protobuf/struct";
