// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.29.3
// source: public/team.proto

/* eslint-disable */
import type { PaginationRequest, PaginationResponse } from "../common";

/** Team member role within a team */
export enum TeamMemberRole {
  TEAM_MEMBER_ROLE_UNSPECIFIED = "TEAM_MEMBER_ROLE_UNSPECIFIED",
  TEAM_MEMBER_ROLE_MEMBER = "TEAM_MEMBER_ROLE_MEMBER",
  TEAM_MEMBER_ROLE_LEAD = "TEAM_MEMBER_ROLE_LEAD",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** Team within an organization */
export interface Team {
  id: number;
  name: string;
  description: string;
  /** User ID of team lead */
  leaderId?:
    | number
    | undefined;
  /** User who created the team */
  createdBy: number;
  /** Computed field */
  memberCount: number;
  creationDate?: Date | undefined;
  lastUpdate?: Date | undefined;
}

/** Team membership record */
export interface TeamMember {
  teamId: number;
  userId: number;
  role: TeamMemberRole;
  addedAt?: Date | undefined;
  addedBy: number;
}

/** Team member with user details (for listing team members) */
export interface TeamMemberWithUser {
  userId: number;
  userName: string;
  email: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  role: TeamMemberRole;
  addedAt?: Date | undefined;
}

/** Request to create a new team */
export interface CreateTeamRequest {
  name: string;
  description?:
    | string
    | undefined;
  /** Defaults to creator if not specified */
  leaderId?: number | undefined;
}

/** Request to update a team */
export interface UpdateTeamRequest {
  id: number;
  name?: string | undefined;
  description?: string | undefined;
  leaderId?: number | undefined;
}

/** Request to list teams */
export interface ListTeamsRequest {
  pagination?: PaginationRequest | undefined;
  includeMemberCount?: boolean | undefined;
}

/** Response for GET /teams */
export interface ListTeamsResponse {
  teams: Team[];
  pagination?: PaginationResponse | undefined;
}

/** Response for GET /teams/{id} */
export interface GetTeamResponse {
  team?: Team | undefined;
  members: TeamMemberWithUser[];
}

/** Request to add a member to a team */
export interface AddTeamMemberRequest {
  teamId: number;
  userId: number;
  role: TeamMemberRole;
}

/** Request to remove a member from a team */
export interface RemoveTeamMemberRequest {
  teamId: number;
  userId: number;
}

/** Request to update a team member's role */
export interface UpdateTeamMemberRoleRequest {
  teamId: number;
  userId: number;
  role: TeamMemberRole;
}

/** Request to list current user's teams */
export interface ListUserTeamsRequest {
  pagination?: PaginationRequest | undefined;
}

/** Response for GET /users/me/teams */
export interface ListUserTeamsResponse {
  teams: Team[];
  pagination?: PaginationResponse | undefined;
}
