# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal/agent.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'internal/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14internal/agent.proto\x12\x11\x65\x63homind.internal\x1a\x1cgoogle/protobuf/struct.proto\"\xcb\x01\n\x0b\x41gentMemory\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x32\n\x0bmemory_type\x18\x03 \x01(\x0e\x32\x1d.echomind.internal.MemoryType\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x19\n\x0c\x65mbedding_id\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x10importance_score\x18\x06 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65ss_count\x18\x07 \x01(\x05\x42\x0f\n\r_embedding_id\"\x88\x01\n\x08ToolCall\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12+\n\nparameters\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\'\n\x06result\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x13\n\x0b\x64uration_ms\x18\x04 \x01(\x05\"{\n\x08PlanStep\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\x12,\n\x06result\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x88\x01\x01\x42\t\n\x07_result\"}\n\x0c\x41gentRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\r\n\x05query\x18\x03 \x01(\t\x12\x39\n\x11relevant_memories\x18\x04 \x03(\x0b\x32\x1e.echomind.internal.AgentMemory\"\x92\x01\n\rAgentResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12/\n\ntool_calls\x18\x02 \x03(\x0b\x32\x1b.echomind.internal.ToolCall\x12)\n\x04plan\x18\x03 \x03(\x0b\x32\x1b.echomind.internal.PlanStep\x12\x13\n\x0btokens_used\x18\x04 \x01(\x05*y\n\nMemoryType\x12\x1b\n\x17MEMORY_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14MEMORY_TYPE_EPISODIC\x10\x01\x12\x18\n\x14MEMORY_TYPE_SEMANTIC\x10\x02\x12\x1a\n\x16MEMORY_TYPE_PROCEDURAL\x10\x03\x42\x19Z\x17\x65\x63homind/proto/internalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internal.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027echomind/proto/internal'
  _globals['_MEMORYTYPE']._serialized_start=819
  _globals['_MEMORYTYPE']._serialized_end=940
  _globals['_AGENTMEMORY']._serialized_start=74
  _globals['_AGENTMEMORY']._serialized_end=277
  _globals['_TOOLCALL']._serialized_start=280
  _globals['_TOOLCALL']._serialized_end=416
  _globals['_PLANSTEP']._serialized_start=418
  _globals['_PLANSTEP']._serialized_end=541
  _globals['_AGENTREQUEST']._serialized_start=543
  _globals['_AGENTREQUEST']._serialized_end=668
  _globals['_AGENTRESPONSE']._serialized_start=671
  _globals['_AGENTRESPONSE']._serialized_end=817
# @@protoc_insertion_point(module_scope)
