# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import embedding_pb2 as internal_dot_embedding__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in internal/embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbedServiceStub(object):
    """gRPC service for embedding
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/echomind.internal.EmbedService/Embed',
                request_serializer=internal_dot_embedding__pb2.EmbedRequest.SerializeToString,
                response_deserializer=internal_dot_embedding__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.GetDimension = channel.unary_unary(
                '/echomind.internal.EmbedService/GetDimension',
                request_serializer=internal_dot_embedding__pb2.DimensionRequest.SerializeToString,
                response_deserializer=internal_dot_embedding__pb2.DimensionResponse.FromString,
                _registered_method=True)


class EmbedServiceServicer(object):
    """gRPC service for embedding
    """

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDimension(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=internal_dot_embedding__pb2.EmbedRequest.FromString,
                    response_serializer=internal_dot_embedding__pb2.EmbedResponse.SerializeToString,
            ),
            'GetDimension': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDimension,
                    request_deserializer=internal_dot_embedding__pb2.DimensionRequest.FromString,
                    response_serializer=internal_dot_embedding__pb2.DimensionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echomind.internal.EmbedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('echomind.internal.EmbedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbedService(object):
    """gRPC service for embedding
    """

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echomind.internal.EmbedService/Embed',
            internal_dot_embedding__pb2.EmbedRequest.SerializeToString,
            internal_dot_embedding__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDimension(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echomind.internal.EmbedService/GetDimension',
            internal_dot_embedding__pb2.DimensionRequest.SerializeToString,
            internal_dot_embedding__pb2.DimensionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
