# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal/projector.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'internal/projector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18internal/projector.proto\x12\x11\x65\x63homind.internal\"\xc0\x01\n\x18ProjectorGenerateRequest\x12\x0e\n\x06viz_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63ollection_name\x18\x02 \x01(\t\x12\x19\n\x0csearch_query\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\x14\n\x07team_id\x18\x05 \x01(\x05H\x01\x88\x01\x01\x12\x13\n\x06org_id\x18\x06 \x01(\x05H\x02\x88\x01\x01\x42\x0f\n\r_search_queryB\n\n\x08_team_idB\t\n\x07_org_idB\x19Z\x17\x65\x63homind/proto/internalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internal.projector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027echomind/proto/internal'
  _globals['_PROJECTORGENERATEREQUEST']._serialized_start=48
  _globals['_PROJECTORGENERATEREQUEST']._serialized_end=240
# @@protoc_insertion_point(module_scope)
