# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: public/user.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'public/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from .. import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11public/user.proto\x12\x0f\x65\x63homind.public\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\xc9\x01\n\x0fUserPreferences\x12!\n\x14\x64\x65\x66\x61ult_assistant_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\r\n\x05theme\x18\x02 \x01(\t\x12<\n\x06\x63ustom\x18\x03 \x03(\x0b\x32,.echomind.public.UserPreferences.CustomEntry\x1a-\n\x0b\x43ustomEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x17\n\x15_default_assistant_id\"\xd8\x02\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\nfirst_name\x18\x04 \x01(\t\x12\x11\n\tlast_name\x18\x05 \x01(\t\x12\r\n\x05roles\x18\x06 \x03(\t\x12\x0e\n\x06groups\x18\x07 \x03(\t\x12\x35\n\x0bpreferences\x18\x08 \x01(\x0b\x32 .echomind.public.UserPreferences\x12\x11\n\tis_active\x18\t \x01(\x08\x12\x31\n\rcreation_date\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0blast_update\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nlast_login\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xad\x01\n\x11UpdateUserRequest\x12\x17\n\nfirst_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tlast_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12:\n\x0bpreferences\x18\x03 \x01(\x0b\x32 .echomind.public.UserPreferencesH\x02\x88\x01\x01\x42\r\n\x0b_first_nameB\x0c\n\n_last_nameB\x0e\n\x0c_preferences\"=\n\x16GetCurrentUserResponse\x12#\n\x04user\x18\x01 \x01(\x0b\x32\x15.echomind.public.User\"p\n\x10ListUsersRequest\x12\x36\n\npagination\x18\x01 \x01(\x0b\x32\".echomind.common.PaginationRequest\x12\x16\n\tis_active\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\x0c\n\n_is_active\"r\n\x11ListUsersResponse\x12$\n\x05users\x18\x01 \x03(\x0b\x32\x15.echomind.public.User\x12\x37\n\npagination\x18\x02 \x01(\x0b\x32#.echomind.common.PaginationResponseB\x17Z\x15\x65\x63homind/proto/publicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025echomind/proto/public'
  _globals['_USERPREFERENCES_CUSTOMENTRY']._loaded_options = None
  _globals['_USERPREFERENCES_CUSTOMENTRY']._serialized_options = b'8\001'
  _globals['_USERPREFERENCES']._serialized_start=86
  _globals['_USERPREFERENCES']._serialized_end=287
  _globals['_USERPREFERENCES_CUSTOMENTRY']._serialized_start=217
  _globals['_USERPREFERENCES_CUSTOMENTRY']._serialized_end=262
  _globals['_USER']._serialized_start=290
  _globals['_USER']._serialized_end=634
  _globals['_UPDATEUSERREQUEST']._serialized_start=637
  _globals['_UPDATEUSERREQUEST']._serialized_end=810
  _globals['_GETCURRENTUSERRESPONSE']._serialized_start=812
  _globals['_GETCURRENTUSERRESPONSE']._serialized_end=873
  _globals['_LISTUSERSREQUEST']._serialized_start=875
  _globals['_LISTUSERSREQUEST']._serialized_end=987
  _globals['_LISTUSERSRESPONSE']._serialized_start=989
  _globals['_LISTUSERSRESPONSE']._serialized_end=1103
# @@protoc_insertion_point(module_scope)
